/* EA7500 */

#define BOARD_PID		"EA7500"
#define BOARD_NAME		"EA7500"
#define BOARD_DESC		"EA7500 Wireless Router"
#define BOARD_VENDOR_NAME	"LINKSYS Co., Ltd."
#define BOARD_VENDOR_URL	"https://www.linksys.com/cn/"
#define BOARD_MODEL_URL		"https://www.linksys.com/cn/"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	12
#define BOARD_GPIO_BTN_WPS	17
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_LED_WPS      5
#undef  BOARD_GPIO_LED_ALL
#define  BOARD_GPIO_LED_POWER   10
#undef  BOARD_GPIO_LED_LAN
#define  BOARD_GPIO_LED_WAN    7
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB_ON
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	4
#define BOARD_NUM_ANT_5G_RX	4
#define BOARD_NUM_ANT_2G_TX	4
#define BOARD_NUM_ANT_2G_RX	4
#define BOARD_NUM_ETH_LEDS	2
#define BOARD_NUM_ETH_EPHY	5
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_USB_PORT_SWAP	1
